language: ruby
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
cache: bundler
rvm:
  - 2.2.4
  - 2.3.0
  - 2.3.1
branches:
  only:
    - master
install:
  - "travis_retry bundle install --jobs 8"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
deploy:
  provider: rubygems
  api_key:
    secure: zyfyt22h4LvT+S5hku65RfTP6++mdiyQsUpR9NMYWE0az+bEsYsmsjl6p4utmA5XahWC5dYBZBJ035XXO142FnPsng9ZyEz3UcYjtUcg3u6i9WFywD1a65Ook+PGWMzhTHRyDx9C+4n9s6UDTF5ERJR/sNW+G7qweo5xU2i5SdAvtRYVTaosPYclEKz6HOGwC4Y8265Miqnib+uXkWq5tq9zXfisUK5CVl4lVjTglxw//cqoWl50d9BNYRZOvHBWOYImjZJcyjQSkH0mWAYRT+K0UcpKdmgCbkfTY+H73Hr+v2j2WUlSi8kz+8ENnZopwlFd+/i9t/DMSZUx4JSSPno0vQC1honoI55+4ZO2ZexJpyJYv0x7kAq1pxisxklbvlmumhkgla9wgpTOpEBNJSawAMKgxKa1BUK024/9UUqI/vjeMPL2/k2mUefu774lZg/iNQTsHGlPqi/a3VXX8gNE98hO4tQJmC6/Hlp+0xrXtMgCkNFSgM/FgJ7DDyxYM02yU7zX/yQJ4indtxBPK702WHkqBc8FWAgdekzl+Re/NI7Bii+q+rzID/ZkubC6NYjXhe53rl51leckbp925URMijBc04M6qj4FC59qS79wG/A8bTtVKVML3rnwwjUOVDbycB2/6WTwBtFAQHzcY3jCsHwKjsS9oweUe8936Nw=
  gem: parasut_rails
  on:
    repo: ahtung/parasut_rails
